/*
 * Ultimaker 3 API
 * REST api for the Ultimaker 3 - 3D printer.  Authentication: Any PUT/POST/DELETE api requires authentication before it can be used. Authentication is done with http digest (RFC 2617) without fallback to basic authentication.  To get a valid username/password combination, the following process can/should be followed.  1) POST /auth/request with 'application' and 'user' as parameters. The application name and user name will be shown to the user on the printer. The reply body will contain a json reply with an 'id' and 'key' part.  2) Repeatedly GET /auth/check/<id> until it reports 'authorized' or 'unauthorized'. This will be reported back once the end user selects if the application is allowed to use the API.  3) [optional] test the authentication, the earlier given 'id' is the username, the 'key' is the password. Use digest authentication on GET /auth/verify to test this.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * Material
 */
public class Material {
  @SerializedName("length_remaining")
  private BigDecimal lengthRemaining = null;

  @SerializedName("GUID")
  private String GUID = null;

  public Material lengthRemaining(BigDecimal lengthRemaining) {
    this.lengthRemaining = lengthRemaining;
    return this;
  }

   /**
   * mm of filament remaining on spool. Returns -1 if the remaining length is unknown.
   * @return lengthRemaining
  **/
  @ApiModelProperty(value = "mm of filament remaining on spool. Returns -1 if the remaining length is unknown.")
  public BigDecimal getLengthRemaining() {
    return lengthRemaining;
  }

  public void setLengthRemaining(BigDecimal lengthRemaining) {
    this.lengthRemaining = lengthRemaining;
  }

  public Material GUID(String GUID) {
    this.GUID = GUID;
    return this;
  }

   /**
   * Unique identifier of the material, empty string if no material loaded.
   * @return GUID
  **/
  @ApiModelProperty(value = "Unique identifier of the material, empty string if no material loaded.")
  public String getGUID() {
    return GUID;
  }

  public void setGUID(String GUID) {
    this.GUID = GUID;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Material material = (Material) o;
    return Objects.equals(this.lengthRemaining, material.lengthRemaining) &&
        Objects.equals(this.GUID, material.GUID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lengthRemaining, GUID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Material {\n");
    
    sb.append("    lengthRemaining: ").append(toIndentedString(lengthRemaining)).append("\n");
    sb.append("    GUID: ").append(toIndentedString(GUID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

